### ISSUE TITLE
Add to cart not working

### ISSUE THREAD

**Issue by epiklearning** [secretpizzaparty/shopify-connect-for-woocommerce#27]
Hi,

First of all, thanks for this plugin, helps out a lot for what i need to do. But im having an issue, the add to cart button, does not seem to work properly. 

When a its clicked, nothing seems to be added into the cart that pops up on the right hand side. 

Ive set up a test site to build on, and to eventually move over to live. http://www.chrged.com/products/ here is the page having the problem. I have enabled one product in shopify (it has a price, weight, inventory, images, etc) and created this in woocommerece as well, it also has the shopify embed code generated.  

When i click add to cart, nothing happens, then i click the cart menu button to see if anything was added, the same page reloads, but the cart pop up on the right hand side shows up, though it shows up empty.

When i disabled the Shopify Connect for WooCommerce (woocommerce plugin was still enabled) i found that if i clicked CART it would take me to the cart page created by woocommerce and it had the product showing up in the cart with about 7 in amount added, so it looks like the information was being sent in the backend, but it was not showing up in the front end,

Any help would be welcome, 
Thanks.
Kevork Atamian
kevork.atamian@esintl.com

**Comment by jkudish** [comment]
Hi Kevork,

Thanks for trying out the plugin and for reporting this issue! :)

Sounds like something is maybe not loading correctly on your site. Can you check to see if your browser's developer console has any errors when you access the cart page?

**Comment by jkudish** [comment]
I tried it out on your site and it loads for me; so I am definitely thinking it's an issue specific to your browser. What browser are you using?

**Comment by MCoolU** [comment]
I think I am having the same issue here. I have several plugins for carousels and product grids, etc. When I click those add to cart buttons it says it adds it, but does not add it to the shopify cart. I think it is adding them to the sites cart if that makes any sense. Is there a way to make all add to cart buttons add to to the shopify cart, not just the one we add on the product pages?

**Comment by jkudish** [comment]
@MCoolU what is your site?

**Comment by jkudish** [comment]
I replied privately to @MCoolU after looking at their site. It seems to be an issue with the theme doing something rather custom.

**Comment by MCoolU** [comment]
I tried it with a different theme as well and it still does it. 
-------- Original message --------From: Joey Kudish <notifications@github.com> Date: 10/22/16  5:18 PM  (GMT-08:00) To: secretpizzaparty/shopify-connect-for-woocommerce <shopify-connect-for-woocommerce@noreply.github.com> Cc: MCoolU <MCoolU@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [secretpizzaparty/shopify-connect-for-woocommerce] Add to cart
  not working (#27) 
I replied privately to @MCoolU after looking at their site. It seems to be an issue with the theme doing something rather custom.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/secretpizzaparty/shopify-connect-for-woocommerce","title":"secretpizzaparty/shopify-connect-for-woocommerce","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/secretpizzaparty/shopify-connect-for-woocommerce"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jkudish in #27: I replied privately to @MCoolU after looking at their site. It seems to be an issue with the theme doing something rather custom."}],"action":{"name":"View Issue","url":"https://github.com/secretpizzaparty/shopify-connect-for-woocommerce/issues/27#issuecomment-255561894"}}}

**Comment by ban100** [comment]
I have the issue in my site.  Can you please help me.

**Comment by MCoolU** [comment]
Do you have any woocommerce customizer? I deactivated all of the plugins I had to customize woocommerce products and display, etc. And then it worked for me.

**Comment by jkudish** [comment]
Would be great to figure out which plugin the conflict is with, so we can try to resolve it. Can you try to narrow it down @MCoolU ?

**Comment by ban100** [comment]
@MCoolU 

Can you please tell me which plugin did you deactivated.
I'm using a plugin for customize the product that called Fancy Product designer, but I need it.

Thanks
